### PR TITLE
Updates from lantern

### PR DESCRIPTION
**Pull request by oxtoacart**

### CODE REVIEW

**Comment by oxtoacart** [comment]
@xiam When bringing in changes from the lantern-pro repo, I noticed that go-update diverged between there and here.  Do you know which version is the right one?

**Comment by xiam** [comment]
In this repo we have the bits that I was planning to merge into Lantern, but for now I guess we can use the glide branch.

**Comment by oxtoacart** [comment]
@xiam Ah, so you were already working on merging these?

**Comment by xiam** [comment]
@oxtoacart Yes, that was in progress, but we can easily continue with glide and merge my updates later.

**Comment by oxtoacart** [comment]
@xiam So you mean we should go ahead and merge this into master, and then you can merge your changes into master later?  Or you mean just point flashlight at the glide branch?

**Comment by xiam** [comment]
No, please leave `master` as is and let's use the `glide` branch.

**Comment by oxtoacart** [comment]
@xiam Okay, cool, I'll update flashlight.

**Comment by xiam** [comment]
Closing this and opening https://github.com/getlantern/flashlight/pull/61 to make flashlight use `master`.

**Pull request closed without merging**
